[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[global]
developmentMode = false
